[WIP] Allow searching replays by is-MM and rating type.
ZeroK-RTS/Zero-K-Infrastructure pull request #2787
Opened 2021-01-26 03:22 UTC by Aquanim

2021-01-27 20:04 UTC, maackey commented on Shared/PlasmaShared/ISpringieService/RatingCategory.cs
> +        Any = 0, Casual = 1, Competitive = 2, Planetwars = 3, None = 4
minor - I'd group up "None" and "Any" just in case additional options are added in the future, it'll be less fragmented

2021-01-27 20:15 UTC, maackey commented on Zero-K.info/Controllers/BattlesController.cs
> +
I'm not sure why a temporary variable needs to be created.
`q = q.Where(b => b.IsMatchMaker == model.Matchmaker`
Other places use nullable booleans or int values to represent similar concepts -- I personally think YesNoAny type is dumb, especially if it doesn't simplify working with nullable booleans, but at least its consistent with the other stuff on this page. 

The conditional is redundant around the switch statement. 
`switch (model.Rating)
{
...
default: 
// default case has no filtering and is effectively equivalent to "any"
}`

2021-01-27 20:17 UTC, maackey commented on Zero-K.info/Views/Battles/BattleDetail.cshtml
> +</tr>
Shouldn't Model.GetRatingCategory() return "None" if Model.IsRatedMatch() is false? That would greatly simplify the view, which IMO shouldn't have lots of logic embedded -- it gets messy and hard to style.

2021-01-27 20:22 UTC, maackey reviewed
Just a few minor suggestions after glancing it over.

2021-01-28 09:03 UTC, Licho1 requested changes

2021-01-28 09:03 UTC, Licho1 commented on Zero-K.info/Controllers/BattlesController.cs
> +                        q = q.Where(b => b.ApplicableRatings.HasFlag(RatingCategoryFlags.Casual));
Has flag wont have translation to SQL so this wont work. It would crash unless you dod ToList before. And if you do you are copying battles to memory

2021-01-30 06:27 UTC, Aquanim commented
> minor - I'd group up "None" and "Any" just in case additional options are added in the future, it'll be less fragmented
Good point.

> Shouldn't Model.GetRatingCategory() return "None" if Model.IsRatedMatch() is false? That would greatly simplify the view, which IMO shouldn't have lots of logic embedded -- it gets messy and hard to style.
That seems like a reasonable take to me, but outside the scope of this PR.

> The conditional is redundant around the switch statement.
It is, but that applies to the conditionals around some of the other switch statements previously existing in this file as well so I followed the convention. I assume the purpose is to make the categories easier to extend in the future without making mistakes.

> Has flag wont have translation to SQL so this wont work. It would crash unless you dod ToList before. And if you do you are copying battles to memory
https://github.com/dotnet/efcore/issues/2852 suggests that HasFlag does have a translation as of 2016. Certainly it did not throw an error like b.IsRatedMatch() did when I used it in the same place. Can you confirm that this is a problem?

2021-01-31 12:09 UTC, Licho1 commented on Zero-K.info/Controllers/BattlesController.cs
> +
Nullable value is fine, we just lacked gui component to represent that ..

2024-04-06 10:06 UTC, Licho1 commented on Zero-K.info/Controllers/BattlesController.cs
> +                        q = q.Where(b => b.ApplicableRatings.HasFlag(RatingCategoryFlags.Casual));
To resolve this use condition like this (b.ApplicableRating & RatingCategoryFlags.Casual) = RatingCategoryFlags.Casual

2024-04-06 10:17 UTC, Licho1 approved these changes

2024-04-06 10:19 UTC, merged